"""Requires fonttools[woff]. Keeps original font files and all non-Latin glyphs as an on-demand fallback."""
from pathlib import Path
from hashlib import sha256
import json
from fontTools import subset
from fontTools.ttLib import TTFont
root = Path(__file__).resolve().parent.parent
core = set(range(0x100)) | set(range(0x2000, 0x2070)) | {0x131,0x152,0x153,0x2bb,0x2bc,0x2c6,0x2da,0x2dc,0x304,0x308,0x329,0x20ac,0x2122,0x2191,0x2193,0x2212,0x2215,0xfeff,0xfffd}
# Include current source/data characters, including arrows, names, and review text.
for path in (root/'src').rglob('*'):
    if path.suffix in {'.ts','.tsx','.json'}:
        core.update(map(ord, path.read_text()))
def ranges(points):
    parts=[]
    for p in sorted(points):
        if parts and parts[-1][1]+1==p: parts[-1][1]=p
        else: parts.append([p,p])
    return ','.join(f'U+{a:04X}' if a==b else f'U+{a:04X}-{b:04X}' for a,b in parts)
css=['/* Generated by scripts/subset-fonts.py. Original glyph coverage remains available on demand. */']
manifest={}
out=root/'public/fonts/subsets'; out.mkdir(exist_ok=True)
for style,weight in [('Regular',400),('Medium',500)]:
    font=TTFont(root/f'public/fonts/OpenRunde-{style}.woff2', recalcTimestamp=False)
    remaining=set(font.getBestCmap())-core
    options=subset.Options(); options.flavor='woff2'; options.layout_features=['*']
    engine=subset.Subsetter(options=options); engine.populate(unicodes=core); engine.subset(font)
    temp=out/f'OpenRunde-{style}.woff2'; font.save(temp)
    data=temp.read_bytes(); name=f'OpenRunde-{style}-{sha256(data).hexdigest()[:10]}.woff2'; temp.rename(out/name)
    url=f'/fonts/subsets/{name}'; manifest[style]=url
    for src,points in [(f'/fonts/OpenRunde-{style}.woff2',remaining),(url,core)]:
        css.append(f"@font-face {{font-family: 'OpenRunde'; src: url('{src}') format('woff2'); font-weight: {weight}; font-style: normal; font-display: swap; unicode-range: {ranges(points)};}}")
# Newsreader sources use the original Google's Latin subsets, with both variable axes intact.
for style in ['Regular','Italic']:
    source=root/f'public/fonts/Newsreader-{style}.woff2'
    data=source.read_bytes(); name=f'Newsreader-{style}-{sha256(data).hexdigest()[:10]}.woff2'; (out/name).write_bytes(data)
    css.append(f"@font-face {{font-family: 'Newsreader'; src: url('/fonts/subsets/{name}') format('woff2'); font-weight: 200 800; font-style: {'italic' if style=='Italic' else 'normal'}; font-display: swap; unicode-range: {ranges(core)};}}")
(root/'src/styles/fonts.css').write_text('\n\n'.join(css)+'\n')
(root/'src/data/font-assets.json').write_text(json.dumps(manifest,indent=2)+'\n')
print({name:(out/Path(url).name).stat().st_size for name,url in manifest.items()})
